#!/bin/sh -e
redo-ifchange ./cxx ./cxxflags ./cppflags ./cc ./ccflags
read cc < ./cc
read ccflags < ./ccflags
read cxx < ./cxx
read cxxflags < ./cxxflags
read cppflags < ./cppflags
if g++ -E --usage >/dev/null 2>&1
then
	(cd "$4" && ${cc} ${ccflags} ${cppflags} -o "$1" -c "$2")
	g++ -E ${ccflags} ${cppflags} "$4/$2" -MD -MF "$4/$3" >/dev/null || true
	. "$4/$3" || true
else
        (cd "$4" && ${cc} ${ccflags} ${cppflags} -o "$1" -c "$2" -MMD -MF "$3")
        sed -e "s!^$1: *!!" -e 's/\\$//g' -e "s! \<!&$4/!g" -e "s!^!$4/!" "$4/$3" | xargs -r redo-ifchange
fi
