#!/bin/sh -e
# See http://skarnet.org./software/compile.html
if [ \! -d package ] || [ \! -d source ]
then
	echo "You are not in the right directory." 1>&2
	exit 100
fi

# Create and populate the build directory.
install -d -m 0755 build
if test -r /etc/redhat-release
then
	paxlink=""
else
	paxlink="-l"
fi
( cd source && ( 2>/dev/null pax -w -r ${paxlink} -u -- * ../build/ || true ) )
